# Generated by Django 5.0.6 on 2024-05-29 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='Sin Nombre', max_length=150, verbose_name='Apellidos y Nombres')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%y/%m/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%y/%m/%d')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('date_update', models.DateField(auto_now_add=True, verbose_name='Fecha de Modificación')),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Los Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
