# Generated by Django 5.0.6 on 2024-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_category_alter_type_options_employee_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
